### ISSUE TITLE
Refresh widget 

### ISSUE THREAD

**Issue by ghost** [xRoker/GHCWidget#1]
There is currently no way to refresh the widget's data manually. 

Would you be willing to accept a pull request for this functionality? I would like to help out if possible. 

Thanks!

**Comment by yeusiukou** [comment]
Hi! Sorry for the late reply, yeah, no problem :)

**Comment by ghost** [comment]
Great, thanks! I'll make a pull request so next chance I get.

**Comment by ghost** [comment]
Eh, apologies for all the change in status, I clicked close before comment :)
