### ISSUE TITLE
GitHub Contributions Widget Not Work Now

### ISSUE THREAD

**Issue by lovemyliwu** [xRoker/GHCWidget#10]
can you please fix it?

**Comment by yeusiukou** [comment]
Hi, @lovemyliwu ! Could you provide more information on what is wrong, please? I would also like to know your smartphone model as well as the Android version. Thanks.

**Comment by lovemyliwu** [comment]
@xRoker sure, mobile type is HTC 10

![wechatimg4](https://cloud.githubusercontent.com/assets/2248369/21581091/28e96000-d05c-11e6-87c1-754144c5913a.png)
![wechatimg5](https://cloud.githubusercontent.com/assets/2248369/21581092/290dcfda-d05c-11e6-8b5b-52ac2730271b.jpeg)

**Comment by yeusiukou** [comment]
it's strange. Have you tried to reboot your phone?

**Comment by lovemyliwu** [comment]
@xRoker uhh, I found out why, It's blocked by GFW, after Enabled VPN the widget back to normal now. Thank you for listening.
