### ISSUE TITLE
Use Github API

### ISSUE THREAD

**Issue by veyndan** [xRoker/GHCWidget#11]
It appears that you are parsing html instead of just using the API. Using the API would be much easier and should simplify the code significantly. Using the API in conjunction with Retrofit would handle the parsing as well.

I wouldn't mind implementing this myself, but just want a heads up as to whether such a change would be accepted.

**Comment by yeusiukou** [comment]
Hi, when I was writing this widget the contribution info wasn't available through the api. You can surely do it, it would make the code much cleaner. But do you think it is really worth to add an additional library to such a little app?

**Comment by veyndan** [comment]
I could do it without an additional library, but it would make things a lot easier. It depends if one of the features of this app is to be lightweight or not. I personally believe that the pros outweigh the cons of adding an additional dependency such as this, but again it is your call.

Edit: I was just looking at the API, and it seems that the contribution info still isn't available through the API. Sorry about that, I just assumed something as simple as that should be available.

**Comment by yeusiukou** [comment]
No worries, thanks for the interest :)
