### ISSUE TITLE
can't see contributions - stuck on "loading..." and then "loading failed"

### ISSUE THREAD

**Issue by thatkookooguy** [xRoker/GHCWidget#15]
installed this widget on my **Neuxs 5X**, set up my username (*Thatkookooguy*), and even logged in to see private repositories.

But I can't seem to make the widget get my contribution data.

am I missing a step? need to add a webhook or integration or something?

thanks

**Comment by yeusiukou** [comment]
@Thatkookooguy now it should work, thank you for the notice!

**Comment by thatkookooguy** [comment]
@xRoker indeed it works :-)

thanks
