### ISSUE TITLE
Widget is not working

### ISSUE THREAD

**Issue by ghost** [xRoker/GHCWidget#19]
Hi!
I liked your widget a lot! Thanks for the effort. Unfortunately, it's not working on my Android Samsung S8.
See screenshots:

![screenshot_20181228-165109_samsung experience home](https://user-images.githubusercontent.com/7091543/50519238-9ae2d180-0ac2-11e9-830b-612f28465acc.jpg)
![screenshot_20181228-165123_samsung experience home](https://user-images.githubusercontent.com/7091543/50519239-9ae2d180-0ac2-11e9-9fbb-36d535a5a050.jpg)
![screenshot_20181228-165133_ghcwidget](https://user-images.githubusercontent.com/7091543/50519240-9ae2d180-0ac2-11e9-993e-6ca6f27ffc6a.jpg)

**Comment by ghost** [comment]
It's working now.. Contribution BETA broke it

**Comment by yeusiukou** [comment]
Hi @Attrash-Islam, thanks for the feedback! What do you mean by Contribution BETA?

**Comment by ghost** [comment]
Hi! Thanks for responding. There's a nice feature in Github to show contributions in new way. You can activate it by clicking on the contribution customization.

![screenshot_20181229-112925_chrome](https://user-images.githubusercontent.com/7091543/50536429-3163d100-0b5d-11e9-86b6-21e1583d804c.jpg)

It shows you also a graph of PullRequests/CodeReview/Commits/Issues.

I turned it off in order to have your nice widget on my screen :heart_eyes: but I'll be glad to get it back with your widget together.

**Comment by ghost** [comment]
:heart:
