### ISSUE TITLE
does this widget still working?

### ISSUE THREAD

**Issue by AndreGeng** [xRoker/GHCWidget#23]
It takes forever for the contribution data to load on my phone.
Android Version: 9
Phone Model: Honor 9
<img src="https://user-images.githubusercontent.com/3634890/103618511-0e016700-4f6b-11eb-818d-59a693c82073.png" width="200" />

**Comment by AndreGeng** [comment]
@xRoker it seems Android 9 does not including "DefaultHttpClient" by default, I have created [#24](https://github.com/xRoker/GHCWidget/pull/24) which should fix this problem

**Comment by yeusiukou** [comment]
@AndreGeng thank you! This and other fixes have been included in the latest release. Should be available within 24h. Please let me know there are any other issues.

**Comment by AndreGeng** [comment]
Great! 👍
