### ISSUE TITLE
Private contributions show even if you're not logged in

### ISSUE THREAD

**Issue by liviu-** [xRoker/GHCWidget#8]
One of the option spells "Log in (to see private contributions)", but this is not required anymore since 2016-05-16 (https://github.com/blog/2173-more-contributions-on-your-profile) when GitHub changed the interface to show anonymized private contributions.

This is not a big deal, but just FYI :stuck_out_tongue:

**Comment by yeusiukou** [comment]
Thank you @liviu- resolved 👍
